
services:
  rental-postgres:
    image: postgres:15
    container_name: rental-postgres
    restart: always
    environment:
      POSTGRES_DB: rental_db
      POSTGRES_USER: rental
      POSTGRES_PASSWORD: rental123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
