services:
  rentalservice-api:
    build:
      context: ./RentalService.API
      dockerfile: ../Dockerfile
    container_name: rentalservice-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=rental-postgres;Database=rental_db;Username=rental;Password=rental123
    depends_on:
      - rental-postgres

  rental-postgres:
    image: postgres:15
    container_name: rental-postgres
    restart: always
    environment:
      POSTGRES_DB: rental_db
      POSTGRES_USER: rental
      POSTGRES_PASSWORD: rental123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
